In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
d=pd.read_csv("myn.csv")

C:\Users\sanju\AppData\Local\Temp\ipykernel_16436\1129075072.py:1: DtypeWarning: Columns (0: DiscountOffer) have mixed types. Specify dtype option on import or set low_memory=False.
  d=pd.read_csv("myn.csv")

In [4]:
d.shape

(526564, 13)

In [5]:
d.head()

,URL,Product_id,BrandName,Category,Individual_category,category_by_Gender,Description,DiscountPrice (in Rs),OriginalPrice (in Rs),DiscountOffer,SizeOption,Ratings,Reviews
0,https://www.myntra.com/jeans/roadster/roadster...,2296012,Roadster,Bottom Wear,jeans,Men,roadster men navy blue slim fit mid rise clean...,824.0,1499.0,45% OFF,"28, 30, 32, 34, 36",3.9,999.0
1,https://www.myntra.com/track-pants/locomotive/...,13780156,LOCOMOTIVE,Bottom Wear,track-pants,Men,locomotive men black white solid slim fit tra...,517.0,1149.0,55% OFF,"S, M, L, XL",4.0,999.0
2,https://www.myntra.com/shirts/roadster/roadste...,11895958,Roadster,Topwear,shirts,Men,roadster men navy white black geometric print...,629.0,1399.0,55% OFF,"38, 40, 42, 44, 46, 48",4.3,999.0
3,https://www.myntra.com/shapewear/zivame/zivame...,4335679,Zivame,Lingerie & Sleep Wear,shapewear,Women,zivame women black saree shapewear zi3023core0...,893.0,1295.0,31% OFF,"S, M, L, XL, XXL",4.2,999.0
4,https://www.myntra.com/tshirts/roadster/roadst...,11690882,Roadster,Western,tshirts,Women,roadster women white solid v neck pure cotton ...,NaN,599.0,35% OFF,"XS, S, M, L, XL",4.2,999.0

In [6]:
d.dtypes

URL                          str
Product_id                 int64
BrandName                    str
Category                     str
Individual_category          str
category_by_Gender           str
Description                  str
DiscountPrice (in Rs)    float64
OriginalPrice (in Rs)    float64
DiscountOffer                str
SizeOption                   str
Ratings                  float64
Reviews                  float64
dtype: object

In [8]:
d.isnull().sum()

URL                           0
Product_id                    0
BrandName                     0
Category                      0
Individual_category           0
category_by_Gender            0
Description                   0
DiscountPrice (in Rs)    193158
OriginalPrice (in Rs)         0
DiscountOffer             74306
SizeOption                    0
Ratings                  336152
Reviews                  336152
dtype: int64

In [9]:
d.describe()

,Product_id,DiscountPrice (in Rs),OriginalPrice (in Rs),Ratings,Reviews
count,5.265640e+05,333406.000000,526564.000000,190412.000000,190412.000000
mean,1.506939e+07,1237.444401,2414.068615,4.094892,61.990820
std,3.225710e+06,1052.063517,1916.962914,0.494158,125.714537
min,2.739900e+04,127.000000,99.000000,1.000000,0.000000
25%,1.388053e+07,659.000000,1299.000000,3.900000,8.000000
50%,1.597106e+07,952.000000,1999.000000,4.200000,18.000000
75%,1.734741e+07,1469.000000,2899.000000,4.400000,52.000000
max,1.846435e+07,27996.000000,90000.000000,5.000000,999.000000

In [10]:
d.rename(columns={
    'DiscountPrice (in Rs)': 'DiscountPrice',
    'OriginalPrice (in Rs)': 'OriginalPrice'
}, inplace=True)

In [12]:
d.dropna(subset=['DiscountPrice', 'Ratings', 'Reviews'], inplace=True)

In [13]:
d.shape

(117565, 13)

In [14]:
d['DiscountPercent'] = ((d['OriginalPrice'] - d['DiscountPrice']) / d['OriginalPrice']) * 100
d['DiscountPercent'] = d['DiscountPercent'].round(2)

In [16]:
d['Revenue'] = d['DiscountPrice'] * d['Reviews']

print(d[['BrandName', 'DiscountPrice', 'Reviews', 'Revenue']].head())

    BrandName  DiscountPrice  Reviews   Revenue
0    Roadster          824.0    999.0  823176.0
1  LOCOMOTIVE          517.0    999.0  516483.0
2    Roadster          629.0    999.0  628371.0
3      Zivame          893.0    999.0  892107.0
6  HIGHLANDER          599.0    998.0  597802.0

In [18]:
print(d.isnull().sum())

URL                     0
Product_id              0
BrandName               0
Category                0
Individual_category     0
category_by_Gender      0
Description             0
DiscountPrice           0
OriginalPrice           0
DiscountOffer          24
SizeOption              0
Ratings                 0
Reviews                 0
DiscountPercent         0
Revenue                 0
dtype: int64

In [ ]:
d.shape

(117565, 15)